// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv2_1_HH_
#define _conv2_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "my_net_hadd_16ns_cud.h"
#include "my_net_hmul_16ns_dEe.h"
#include "conv2_1_conv1_weibkb.h"

namespace ap_rtl {

struct conv2_1 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<16> > input_r_q0;
    sc_in< sc_lv<2> > input_offset;
    sc_in< sc_lv<5> > weight_offset;
    sc_out< sc_lv<10> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<16> > output_r_d0;
    sc_in< sc_lv<16> > output_r_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    conv2_1(sc_module_name name);
    SC_HAS_PROCESS(conv2_1);

    ~conv2_1();

    sc_trace_file* mVcdFile;

    conv2_1_conv1_weibkb* conv1_weight_U;
    my_net_hadd_16ns_cud<1,5,16,16,16>* my_net_hadd_16ns_cud_U1;
    my_net_hmul_16ns_dEe<1,4,16,16,16>* my_net_hmul_16ns_dEe_U2;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<11> > conv1_weight_address0;
    sc_signal< sc_logic > conv1_weight_ce0;
    sc_signal< sc_lv<16> > conv1_weight_q0;
    sc_signal< sc_lv<12> > mul_ln19_fu_206_p2;
    sc_signal< sc_lv<12> > mul_ln19_reg_376;
    sc_signal< sc_lv<5> > r_fu_218_p2;
    sc_signal< sc_lv<5> > r_reg_384;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<11> > sub_ln19_fu_248_p2;
    sc_signal< sc_lv<11> > sub_ln19_reg_389;
    sc_signal< sc_lv<1> > icmp_ln8_fu_212_p2;
    sc_signal< sc_lv<5> > c_fu_264_p2;
    sc_signal< sc_lv<5> > c_reg_397;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<10> > output_addr_reg_402;
    sc_signal< sc_lv<1> > icmp_ln11_fu_258_p2;
    sc_signal< sc_lv<5> > zext_ln14_fu_284_p1;
    sc_signal< sc_lv<5> > zext_ln14_reg_407;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > kr_fu_294_p2;
    sc_signal< sc_lv<3> > kr_reg_415;
    sc_signal< sc_lv<5> > add_ln19_1_fu_300_p2;
    sc_signal< sc_lv<5> > add_ln19_1_reg_420;
    sc_signal< sc_lv<1> > icmp_ln14_fu_288_p2;
    sc_signal< sc_lv<5> > shl_ln_fu_306_p3;
    sc_signal< sc_lv<5> > shl_ln_reg_425;
    sc_signal< sc_lv<3> > kc_fu_324_p2;
    sc_signal< sc_lv<3> > kc_reg_433;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln17_fu_318_p2;
    sc_signal< sc_lv<16> > input_load_reg_448;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<16> > conv1_weight_load_reg_453;
    sc_signal< sc_lv<16> > grp_fu_162_p2;
    sc_signal< sc_lv<16> > tmp_reg_458;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<16> > output_load_reg_463;
    sc_signal< sc_lv<16> > grp_fu_158_p2;
    sc_signal< sc_lv<16> > tmp_s_reg_468;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<5> > r_0_reg_112;
    sc_signal< sc_lv<5> > c_0_reg_124;
    sc_signal< sc_lv<3> > kr_0_reg_136;
    sc_signal< sc_lv<3> > kc_0_reg_147;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > zext_ln19_1_fu_279_p1;
    sc_signal< sc_lv<64> > tmp_19_fu_336_p5;
    sc_signal< sc_lv<64> > sext_ln19_3_fu_366_p1;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<7> > tmp_18_fu_170_p3;
    sc_signal< sc_lv<8> > zext_ln19_3_fu_178_p1;
    sc_signal< sc_lv<8> > zext_ln19_fu_166_p1;
    sc_signal< sc_lv<8> > sub_ln19_1_fu_182_p2;
    sc_signal< sc_lv<9> > sext_ln19_1_fu_188_p1;
    sc_signal< sc_lv<9> > zext_ln19_5_fu_192_p1;
    sc_signal< sc_lv<9> > add_ln19_3_fu_196_p2;
    sc_signal< sc_lv<9> > mul_ln19_fu_206_p0;
    sc_signal< sc_lv<10> > shl_ln19_1_fu_224_p3;
    sc_signal< sc_lv<7> > shl_ln19_2_fu_236_p3;
    sc_signal< sc_lv<11> > zext_ln19_2_fu_232_p1;
    sc_signal< sc_lv<11> > zext_ln19_4_fu_244_p1;
    sc_signal< sc_lv<11> > zext_ln11_fu_254_p1;
    sc_signal< sc_lv<11> > add_ln19_fu_270_p2;
    sc_signal< sc_lv<32> > sext_ln19_fu_275_p1;
    sc_signal< sc_lv<5> > zext_ln17_fu_314_p1;
    sc_signal< sc_lv<5> > add_ln19_2_fu_330_p2;
    sc_signal< sc_lv<5> > add_ln19_5_fu_347_p2;
    sc_signal< sc_lv<5> > add_ln19_4_fu_352_p2;
    sc_signal< sc_lv<12> > zext_ln19_6_fu_357_p1;
    sc_signal< sc_lv<12> > add_ln19_6_fu_361_p2;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_fsm_state1;
    static const sc_lv<16> ap_ST_fsm_state2;
    static const sc_lv<16> ap_ST_fsm_state3;
    static const sc_lv<16> ap_ST_fsm_state4;
    static const sc_lv<16> ap_ST_fsm_state5;
    static const sc_lv<16> ap_ST_fsm_state6;
    static const sc_lv<16> ap_ST_fsm_state7;
    static const sc_lv<16> ap_ST_fsm_state8;
    static const sc_lv<16> ap_ST_fsm_state9;
    static const sc_lv<16> ap_ST_fsm_state10;
    static const sc_lv<16> ap_ST_fsm_state11;
    static const sc_lv<16> ap_ST_fsm_state12;
    static const sc_lv<16> ap_ST_fsm_state13;
    static const sc_lv<16> ap_ST_fsm_state14;
    static const sc_lv<16> ap_ST_fsm_state15;
    static const sc_lv<16> ap_ST_fsm_state16;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<12> ap_const_lv12_19;
    static const sc_lv<5> ap_const_lv5_1C;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<52> ap_const_lv52_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_add_ln19_1_fu_300_p2();
    void thread_add_ln19_2_fu_330_p2();
    void thread_add_ln19_3_fu_196_p2();
    void thread_add_ln19_4_fu_352_p2();
    void thread_add_ln19_5_fu_347_p2();
    void thread_add_ln19_6_fu_361_p2();
    void thread_add_ln19_fu_270_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_c_fu_264_p2();
    void thread_conv1_weight_address0();
    void thread_conv1_weight_ce0();
    void thread_icmp_ln11_fu_258_p2();
    void thread_icmp_ln14_fu_288_p2();
    void thread_icmp_ln17_fu_318_p2();
    void thread_icmp_ln8_fu_212_p2();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_kc_fu_324_p2();
    void thread_kr_fu_294_p2();
    void thread_mul_ln19_fu_206_p0();
    void thread_mul_ln19_fu_206_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_r_fu_218_p2();
    void thread_sext_ln19_1_fu_188_p1();
    void thread_sext_ln19_3_fu_366_p1();
    void thread_sext_ln19_fu_275_p1();
    void thread_shl_ln19_1_fu_224_p3();
    void thread_shl_ln19_2_fu_236_p3();
    void thread_shl_ln_fu_306_p3();
    void thread_sub_ln19_1_fu_182_p2();
    void thread_sub_ln19_fu_248_p2();
    void thread_tmp_18_fu_170_p3();
    void thread_tmp_19_fu_336_p5();
    void thread_zext_ln11_fu_254_p1();
    void thread_zext_ln14_fu_284_p1();
    void thread_zext_ln17_fu_314_p1();
    void thread_zext_ln19_1_fu_279_p1();
    void thread_zext_ln19_2_fu_232_p1();
    void thread_zext_ln19_3_fu_178_p1();
    void thread_zext_ln19_4_fu_244_p1();
    void thread_zext_ln19_5_fu_192_p1();
    void thread_zext_ln19_6_fu_357_p1();
    void thread_zext_ln19_fu_166_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
