// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv2_HH_
#define _conv2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "my_net_hadd_16ns_cud.h"
#include "my_net_hmul_16ns_dEe.h"
#include "my_net_am_addmul_g8j.h"
#include "conv2_conv2_weight.h"

namespace ap_rtl {

struct conv2 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<16> > input_r_q0;
    sc_in< sc_lv<5> > input_offset;
    sc_in< sc_lv<6> > weight_offset;
    sc_out< sc_lv<7> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<16> > output_r_d0;
    sc_in< sc_lv<16> > output_r_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    conv2(sc_module_name name);
    SC_HAS_PROCESS(conv2);

    ~conv2();

    sc_trace_file* mVcdFile;

    conv2_conv2_weight* conv2_weight_U;
    my_net_hadd_16ns_cud<1,5,16,16,16>* my_net_hadd_16ns_cud_U17;
    my_net_hmul_16ns_dEe<1,4,16,16,16>* my_net_hmul_16ns_dEe_U18;
    my_net_am_addmul_g8j<1,1,5,10,6,15>* my_net_am_addmul_g8j_U19;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<14> > conv2_weight_address0;
    sc_signal< sc_logic > conv2_weight_ce0;
    sc_signal< sc_lv<16> > conv2_weight_q0;
    sc_signal< sc_lv<15> > grp_fu_396_p3;
    sc_signal< sc_lv<15> > mul_ln19_reg_404;
    sc_signal< sc_lv<13> > mul_ln19_1_fu_190_p2;
    sc_signal< sc_lv<13> > mul_ln19_1_reg_409;
    sc_signal< sc_lv<4> > r_fu_202_p2;
    sc_signal< sc_lv<4> > r_reg_417;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<7> > shl_ln19_3_fu_208_p3;
    sc_signal< sc_lv<7> > shl_ln19_3_reg_422;
    sc_signal< sc_lv<1> > icmp_ln8_fu_196_p2;
    sc_signal< sc_lv<5> > shl_ln19_4_fu_216_p3;
    sc_signal< sc_lv<5> > shl_ln19_4_reg_427;
    sc_signal< sc_lv<4> > c_fu_234_p2;
    sc_signal< sc_lv<4> > c_reg_435;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<7> > output_addr_reg_440;
    sc_signal< sc_lv<1> > icmp_ln11_fu_228_p2;
    sc_signal< sc_lv<5> > zext_ln14_1_fu_263_p1;
    sc_signal< sc_lv<5> > zext_ln14_1_reg_445;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > kr_fu_273_p2;
    sc_signal< sc_lv<3> > kr_reg_453;
    sc_signal< sc_lv<9> > sub_ln19_fu_309_p2;
    sc_signal< sc_lv<9> > sub_ln19_reg_458;
    sc_signal< sc_lv<1> > icmp_ln14_fu_267_p2;
    sc_signal< sc_lv<5> > shl_ln_fu_315_p3;
    sc_signal< sc_lv<5> > shl_ln_reg_463;
    sc_signal< sc_lv<3> > kc_fu_337_p2;
    sc_signal< sc_lv<3> > kc_reg_471;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln17_fu_331_p2;
    sc_signal< sc_lv<16> > input_load_reg_486;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<16> > conv2_weight_load_reg_491;
    sc_signal< sc_lv<16> > grp_fu_166_p2;
    sc_signal< sc_lv<16> > tmp_reg_496;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<16> > output_load_reg_501;
    sc_signal< sc_lv<16> > grp_fu_162_p2;
    sc_signal< sc_lv<16> > tmp_s_reg_506;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<4> > r_0_reg_116;
    sc_signal< sc_lv<4> > c_0_reg_128;
    sc_signal< sc_lv<3> > kr_0_reg_140;
    sc_signal< sc_lv<3> > kc_0_reg_151;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > zext_ln19_4_fu_254_p1;
    sc_signal< sc_lv<64> > sext_ln19_4_fu_367_p1;
    sc_signal< sc_lv<64> > sext_ln19_5_fu_391_p1;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<10> > tmp_20_fu_170_p3;
    sc_signal< sc_lv<5> > mul_ln19_1_fu_190_p0;
    sc_signal< sc_lv<5> > zext_ln11_fu_224_p1;
    sc_signal< sc_lv<5> > add_ln19_6_fu_240_p2;
    sc_signal< sc_lv<7> > zext_ln19_6_fu_245_p1;
    sc_signal< sc_lv<7> > add_ln19_fu_249_p2;
    sc_signal< sc_lv<4> > zext_ln14_fu_259_p1;
    sc_signal< sc_lv<4> > add_ln19_1_fu_279_p2;
    sc_signal< sc_lv<8> > shl_ln19_5_fu_285_p3;
    sc_signal< sc_lv<5> > shl_ln19_6_fu_297_p3;
    sc_signal< sc_lv<9> > zext_ln19_8_fu_293_p1;
    sc_signal< sc_lv<9> > zext_ln19_9_fu_305_p1;
    sc_signal< sc_lv<4> > zext_ln17_1_fu_327_p1;
    sc_signal< sc_lv<4> > add_ln19_7_fu_343_p2;
    sc_signal< sc_lv<9> > zext_ln19_10_fu_349_p1;
    sc_signal< sc_lv<9> > add_ln19_3_fu_353_p2;
    sc_signal< sc_lv<13> > sext_ln19_fu_358_p1;
    sc_signal< sc_lv<13> > add_ln19_10_fu_362_p2;
    sc_signal< sc_lv<5> > zext_ln17_fu_323_p1;
    sc_signal< sc_lv<5> > add_ln19_8_fu_372_p2;
    sc_signal< sc_lv<5> > add_ln19_4_fu_377_p2;
    sc_signal< sc_lv<15> > zext_ln19_12_fu_382_p1;
    sc_signal< sc_lv<15> > add_ln19_11_fu_386_p2;
    sc_signal< sc_lv<5> > grp_fu_396_p0;
    sc_signal< sc_lv<10> > grp_fu_396_p1;
    sc_signal< sc_lv<6> > grp_fu_396_p2;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    sc_signal< sc_lv<11> > grp_fu_396_p00;
    sc_signal< sc_lv<11> > grp_fu_396_p10;
    sc_signal< sc_lv<13> > mul_ln19_1_fu_190_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_fsm_state1;
    static const sc_lv<16> ap_ST_fsm_state2;
    static const sc_lv<16> ap_ST_fsm_state3;
    static const sc_lv<16> ap_ST_fsm_state4;
    static const sc_lv<16> ap_ST_fsm_state5;
    static const sc_lv<16> ap_ST_fsm_state6;
    static const sc_lv<16> ap_ST_fsm_state7;
    static const sc_lv<16> ap_ST_fsm_state8;
    static const sc_lv<16> ap_ST_fsm_state9;
    static const sc_lv<16> ap_ST_fsm_state10;
    static const sc_lv<16> ap_ST_fsm_state11;
    static const sc_lv<16> ap_ST_fsm_state12;
    static const sc_lv<16> ap_ST_fsm_state13;
    static const sc_lv<16> ap_ST_fsm_state14;
    static const sc_lv<16> ap_ST_fsm_state15;
    static const sc_lv<16> ap_ST_fsm_state16;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<13> ap_const_lv13_C4;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<15> ap_const_lv15_19;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_add_ln19_10_fu_362_p2();
    void thread_add_ln19_11_fu_386_p2();
    void thread_add_ln19_1_fu_279_p2();
    void thread_add_ln19_3_fu_353_p2();
    void thread_add_ln19_4_fu_377_p2();
    void thread_add_ln19_6_fu_240_p2();
    void thread_add_ln19_7_fu_343_p2();
    void thread_add_ln19_8_fu_372_p2();
    void thread_add_ln19_fu_249_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_c_fu_234_p2();
    void thread_conv2_weight_address0();
    void thread_conv2_weight_ce0();
    void thread_grp_fu_396_p0();
    void thread_grp_fu_396_p00();
    void thread_grp_fu_396_p1();
    void thread_grp_fu_396_p10();
    void thread_grp_fu_396_p2();
    void thread_icmp_ln11_fu_228_p2();
    void thread_icmp_ln14_fu_267_p2();
    void thread_icmp_ln17_fu_331_p2();
    void thread_icmp_ln8_fu_196_p2();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_kc_fu_337_p2();
    void thread_kr_fu_273_p2();
    void thread_mul_ln19_1_fu_190_p0();
    void thread_mul_ln19_1_fu_190_p00();
    void thread_mul_ln19_1_fu_190_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_r_fu_202_p2();
    void thread_sext_ln19_4_fu_367_p1();
    void thread_sext_ln19_5_fu_391_p1();
    void thread_sext_ln19_fu_358_p1();
    void thread_shl_ln19_3_fu_208_p3();
    void thread_shl_ln19_4_fu_216_p3();
    void thread_shl_ln19_5_fu_285_p3();
    void thread_shl_ln19_6_fu_297_p3();
    void thread_shl_ln_fu_315_p3();
    void thread_sub_ln19_fu_309_p2();
    void thread_tmp_20_fu_170_p3();
    void thread_zext_ln11_fu_224_p1();
    void thread_zext_ln14_1_fu_263_p1();
    void thread_zext_ln14_fu_259_p1();
    void thread_zext_ln17_1_fu_327_p1();
    void thread_zext_ln17_fu_323_p1();
    void thread_zext_ln19_10_fu_349_p1();
    void thread_zext_ln19_12_fu_382_p1();
    void thread_zext_ln19_4_fu_254_p1();
    void thread_zext_ln19_6_fu_245_p1();
    void thread_zext_ln19_8_fu_293_p1();
    void thread_zext_ln19_9_fu_305_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
