// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> conv2_1::ap_ST_fsm_state1 = "1";
const sc_lv<16> conv2_1::ap_ST_fsm_state2 = "10";
const sc_lv<16> conv2_1::ap_ST_fsm_state3 = "100";
const sc_lv<16> conv2_1::ap_ST_fsm_state4 = "1000";
const sc_lv<16> conv2_1::ap_ST_fsm_state5 = "10000";
const sc_lv<16> conv2_1::ap_ST_fsm_state6 = "100000";
const sc_lv<16> conv2_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> conv2_1::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> conv2_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv2_1::ap_const_lv32_1 = "1";
const sc_lv<1> conv2_1::ap_const_lv1_0 = "0";
const sc_lv<32> conv2_1::ap_const_lv32_2 = "10";
const sc_lv<32> conv2_1::ap_const_lv32_3 = "11";
const sc_lv<32> conv2_1::ap_const_lv32_4 = "100";
const sc_lv<32> conv2_1::ap_const_lv32_5 = "101";
const sc_lv<32> conv2_1::ap_const_lv32_9 = "1001";
const sc_lv<32> conv2_1::ap_const_lv32_E = "1110";
const sc_lv<5> conv2_1::ap_const_lv5_0 = "00000";
const sc_lv<1> conv2_1::ap_const_lv1_1 = "1";
const sc_lv<3> conv2_1::ap_const_lv3_0 = "000";
const sc_lv<32> conv2_1::ap_const_lv32_F = "1111";
const sc_lv<32> conv2_1::ap_const_lv32_8 = "1000";
const sc_lv<32> conv2_1::ap_const_lv32_A = "1010";
const sc_lv<32> conv2_1::ap_const_lv32_6 = "110";
const sc_lv<2> conv2_1::ap_const_lv2_0 = "00";
const sc_lv<12> conv2_1::ap_const_lv12_19 = "11001";
const sc_lv<5> conv2_1::ap_const_lv5_1C = "11100";
const sc_lv<5> conv2_1::ap_const_lv5_1 = "1";
const sc_lv<3> conv2_1::ap_const_lv3_5 = "101";
const sc_lv<3> conv2_1::ap_const_lv3_1 = "1";
const sc_lv<52> conv2_1::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const bool conv2_1::ap_const_boolean_1 = true;

conv2_1::conv2_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    conv1_weight_U = new conv2_1_conv1_weibkb("conv1_weight_U");
    conv1_weight_U->clk(ap_clk);
    conv1_weight_U->reset(ap_rst);
    conv1_weight_U->address0(conv1_weight_address0);
    conv1_weight_U->ce0(conv1_weight_ce0);
    conv1_weight_U->q0(conv1_weight_q0);
    my_net_hadd_16ns_cud_U1 = new my_net_hadd_16ns_cud<1,5,16,16,16>("my_net_hadd_16ns_cud_U1");
    my_net_hadd_16ns_cud_U1->clk(ap_clk);
    my_net_hadd_16ns_cud_U1->reset(ap_rst);
    my_net_hadd_16ns_cud_U1->din0(output_load_reg_463);
    my_net_hadd_16ns_cud_U1->din1(tmp_reg_458);
    my_net_hadd_16ns_cud_U1->ce(ap_var_for_const0);
    my_net_hadd_16ns_cud_U1->dout(grp_fu_158_p2);
    my_net_hmul_16ns_dEe_U2 = new my_net_hmul_16ns_dEe<1,4,16,16,16>("my_net_hmul_16ns_dEe_U2");
    my_net_hmul_16ns_dEe_U2->clk(ap_clk);
    my_net_hmul_16ns_dEe_U2->reset(ap_rst);
    my_net_hmul_16ns_dEe_U2->din0(input_load_reg_448);
    my_net_hmul_16ns_dEe_U2->din1(conv1_weight_load_reg_453);
    my_net_hmul_16ns_dEe_U2->ce(ap_var_for_const0);
    my_net_hmul_16ns_dEe_U2->dout(grp_fu_162_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln19_1_fu_300_p2);
    sensitive << ( zext_ln14_fu_284_p1 );
    sensitive << ( r_0_reg_112 );

    SC_METHOD(thread_add_ln19_2_fu_330_p2);
    sensitive << ( c_0_reg_124 );
    sensitive << ( zext_ln17_fu_314_p1 );

    SC_METHOD(thread_add_ln19_3_fu_196_p2);
    sensitive << ( sext_ln19_1_fu_188_p1 );
    sensitive << ( zext_ln19_5_fu_192_p1 );

    SC_METHOD(thread_add_ln19_4_fu_352_p2);
    sensitive << ( zext_ln14_reg_407 );
    sensitive << ( add_ln19_5_fu_347_p2 );

    SC_METHOD(thread_add_ln19_5_fu_347_p2);
    sensitive << ( shl_ln_reg_425 );
    sensitive << ( zext_ln17_fu_314_p1 );

    SC_METHOD(thread_add_ln19_6_fu_361_p2);
    sensitive << ( mul_ln19_reg_376 );
    sensitive << ( zext_ln19_6_fu_357_p1 );

    SC_METHOD(thread_add_ln19_fu_270_p2);
    sensitive << ( sub_ln19_reg_389 );
    sensitive << ( zext_ln11_fu_254_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_212_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_212_p2 );

    SC_METHOD(thread_c_fu_264_p2);
    sensitive << ( c_0_reg_124 );

    SC_METHOD(thread_conv1_weight_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sext_ln19_3_fu_366_p1 );

    SC_METHOD(thread_conv1_weight_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_icmp_ln11_fu_258_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c_0_reg_124 );

    SC_METHOD(thread_icmp_ln14_fu_288_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( kr_0_reg_136 );

    SC_METHOD(thread_icmp_ln17_fu_318_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( kc_0_reg_147 );

    SC_METHOD(thread_icmp_ln8_fu_212_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_0_reg_112 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_19_fu_336_p5 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_kc_fu_324_p2);
    sensitive << ( kc_0_reg_147 );

    SC_METHOD(thread_kr_fu_294_p2);
    sensitive << ( kr_0_reg_136 );

    SC_METHOD(thread_mul_ln19_fu_206_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln19_3_fu_196_p2 );

    SC_METHOD(thread_mul_ln19_fu_206_p2);
    sensitive << ( mul_ln19_fu_206_p0 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( output_addr_reg_402 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( tmp_s_reg_468 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_r_fu_218_p2);
    sensitive << ( r_0_reg_112 );

    SC_METHOD(thread_sext_ln19_1_fu_188_p1);
    sensitive << ( sub_ln19_1_fu_182_p2 );

    SC_METHOD(thread_sext_ln19_3_fu_366_p1);
    sensitive << ( add_ln19_6_fu_361_p2 );

    SC_METHOD(thread_sext_ln19_fu_275_p1);
    sensitive << ( add_ln19_fu_270_p2 );

    SC_METHOD(thread_shl_ln19_1_fu_224_p3);
    sensitive << ( r_0_reg_112 );

    SC_METHOD(thread_shl_ln19_2_fu_236_p3);
    sensitive << ( r_0_reg_112 );

    SC_METHOD(thread_shl_ln_fu_306_p3);
    sensitive << ( kr_0_reg_136 );

    SC_METHOD(thread_sub_ln19_1_fu_182_p2);
    sensitive << ( zext_ln19_3_fu_178_p1 );
    sensitive << ( zext_ln19_fu_166_p1 );

    SC_METHOD(thread_sub_ln19_fu_248_p2);
    sensitive << ( zext_ln19_2_fu_232_p1 );
    sensitive << ( zext_ln19_4_fu_244_p1 );

    SC_METHOD(thread_tmp_18_fu_170_p3);
    sensitive << ( weight_offset );

    SC_METHOD(thread_tmp_19_fu_336_p5);
    sensitive << ( input_offset );
    sensitive << ( add_ln19_1_reg_420 );
    sensitive << ( add_ln19_2_fu_330_p2 );

    SC_METHOD(thread_zext_ln11_fu_254_p1);
    sensitive << ( c_0_reg_124 );

    SC_METHOD(thread_zext_ln14_fu_284_p1);
    sensitive << ( kr_0_reg_136 );

    SC_METHOD(thread_zext_ln17_fu_314_p1);
    sensitive << ( kc_0_reg_147 );

    SC_METHOD(thread_zext_ln19_1_fu_279_p1);
    sensitive << ( sext_ln19_fu_275_p1 );

    SC_METHOD(thread_zext_ln19_2_fu_232_p1);
    sensitive << ( shl_ln19_1_fu_224_p3 );

    SC_METHOD(thread_zext_ln19_3_fu_178_p1);
    sensitive << ( tmp_18_fu_170_p3 );

    SC_METHOD(thread_zext_ln19_4_fu_244_p1);
    sensitive << ( shl_ln19_2_fu_236_p3 );

    SC_METHOD(thread_zext_ln19_5_fu_192_p1);
    sensitive << ( input_offset );

    SC_METHOD(thread_zext_ln19_6_fu_357_p1);
    sensitive << ( add_ln19_4_fu_352_p2 );

    SC_METHOD(thread_zext_ln19_fu_166_p1);
    sensitive << ( weight_offset );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_212_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln11_fu_258_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln14_fu_288_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln17_fu_318_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, input_offset, "(port)input_offset");
    sc_trace(mVcdFile, weight_offset, "(port)weight_offset");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, conv1_weight_address0, "conv1_weight_address0");
    sc_trace(mVcdFile, conv1_weight_ce0, "conv1_weight_ce0");
    sc_trace(mVcdFile, conv1_weight_q0, "conv1_weight_q0");
    sc_trace(mVcdFile, mul_ln19_fu_206_p2, "mul_ln19_fu_206_p2");
    sc_trace(mVcdFile, mul_ln19_reg_376, "mul_ln19_reg_376");
    sc_trace(mVcdFile, r_fu_218_p2, "r_fu_218_p2");
    sc_trace(mVcdFile, r_reg_384, "r_reg_384");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln19_fu_248_p2, "sub_ln19_fu_248_p2");
    sc_trace(mVcdFile, sub_ln19_reg_389, "sub_ln19_reg_389");
    sc_trace(mVcdFile, icmp_ln8_fu_212_p2, "icmp_ln8_fu_212_p2");
    sc_trace(mVcdFile, c_fu_264_p2, "c_fu_264_p2");
    sc_trace(mVcdFile, c_reg_397, "c_reg_397");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, output_addr_reg_402, "output_addr_reg_402");
    sc_trace(mVcdFile, icmp_ln11_fu_258_p2, "icmp_ln11_fu_258_p2");
    sc_trace(mVcdFile, zext_ln14_fu_284_p1, "zext_ln14_fu_284_p1");
    sc_trace(mVcdFile, zext_ln14_reg_407, "zext_ln14_reg_407");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, kr_fu_294_p2, "kr_fu_294_p2");
    sc_trace(mVcdFile, kr_reg_415, "kr_reg_415");
    sc_trace(mVcdFile, add_ln19_1_fu_300_p2, "add_ln19_1_fu_300_p2");
    sc_trace(mVcdFile, add_ln19_1_reg_420, "add_ln19_1_reg_420");
    sc_trace(mVcdFile, icmp_ln14_fu_288_p2, "icmp_ln14_fu_288_p2");
    sc_trace(mVcdFile, shl_ln_fu_306_p3, "shl_ln_fu_306_p3");
    sc_trace(mVcdFile, shl_ln_reg_425, "shl_ln_reg_425");
    sc_trace(mVcdFile, kc_fu_324_p2, "kc_fu_324_p2");
    sc_trace(mVcdFile, kc_reg_433, "kc_reg_433");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln17_fu_318_p2, "icmp_ln17_fu_318_p2");
    sc_trace(mVcdFile, input_load_reg_448, "input_load_reg_448");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, conv1_weight_load_reg_453, "conv1_weight_load_reg_453");
    sc_trace(mVcdFile, grp_fu_162_p2, "grp_fu_162_p2");
    sc_trace(mVcdFile, tmp_reg_458, "tmp_reg_458");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, output_load_reg_463, "output_load_reg_463");
    sc_trace(mVcdFile, grp_fu_158_p2, "grp_fu_158_p2");
    sc_trace(mVcdFile, tmp_s_reg_468, "tmp_s_reg_468");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, r_0_reg_112, "r_0_reg_112");
    sc_trace(mVcdFile, c_0_reg_124, "c_0_reg_124");
    sc_trace(mVcdFile, kr_0_reg_136, "kr_0_reg_136");
    sc_trace(mVcdFile, kc_0_reg_147, "kc_0_reg_147");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, zext_ln19_1_fu_279_p1, "zext_ln19_1_fu_279_p1");
    sc_trace(mVcdFile, tmp_19_fu_336_p5, "tmp_19_fu_336_p5");
    sc_trace(mVcdFile, sext_ln19_3_fu_366_p1, "sext_ln19_3_fu_366_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_18_fu_170_p3, "tmp_18_fu_170_p3");
    sc_trace(mVcdFile, zext_ln19_3_fu_178_p1, "zext_ln19_3_fu_178_p1");
    sc_trace(mVcdFile, zext_ln19_fu_166_p1, "zext_ln19_fu_166_p1");
    sc_trace(mVcdFile, sub_ln19_1_fu_182_p2, "sub_ln19_1_fu_182_p2");
    sc_trace(mVcdFile, sext_ln19_1_fu_188_p1, "sext_ln19_1_fu_188_p1");
    sc_trace(mVcdFile, zext_ln19_5_fu_192_p1, "zext_ln19_5_fu_192_p1");
    sc_trace(mVcdFile, add_ln19_3_fu_196_p2, "add_ln19_3_fu_196_p2");
    sc_trace(mVcdFile, mul_ln19_fu_206_p0, "mul_ln19_fu_206_p0");
    sc_trace(mVcdFile, shl_ln19_1_fu_224_p3, "shl_ln19_1_fu_224_p3");
    sc_trace(mVcdFile, shl_ln19_2_fu_236_p3, "shl_ln19_2_fu_236_p3");
    sc_trace(mVcdFile, zext_ln19_2_fu_232_p1, "zext_ln19_2_fu_232_p1");
    sc_trace(mVcdFile, zext_ln19_4_fu_244_p1, "zext_ln19_4_fu_244_p1");
    sc_trace(mVcdFile, zext_ln11_fu_254_p1, "zext_ln11_fu_254_p1");
    sc_trace(mVcdFile, add_ln19_fu_270_p2, "add_ln19_fu_270_p2");
    sc_trace(mVcdFile, sext_ln19_fu_275_p1, "sext_ln19_fu_275_p1");
    sc_trace(mVcdFile, zext_ln17_fu_314_p1, "zext_ln17_fu_314_p1");
    sc_trace(mVcdFile, add_ln19_2_fu_330_p2, "add_ln19_2_fu_330_p2");
    sc_trace(mVcdFile, add_ln19_5_fu_347_p2, "add_ln19_5_fu_347_p2");
    sc_trace(mVcdFile, add_ln19_4_fu_352_p2, "add_ln19_4_fu_352_p2");
    sc_trace(mVcdFile, zext_ln19_6_fu_357_p1, "zext_ln19_6_fu_357_p1");
    sc_trace(mVcdFile, add_ln19_6_fu_361_p2, "add_ln19_6_fu_361_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv2_1::~conv2_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete conv1_weight_U;
    delete my_net_hadd_16ns_cud_U1;
    delete my_net_hmul_16ns_dEe_U2;
}

void conv2_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv2_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_288_p2.read(), ap_const_lv1_1))) {
        c_0_reg_124 = c_reg_397.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln8_fu_212_p2.read(), ap_const_lv1_0))) {
        c_0_reg_124 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        kc_0_reg_147 = kc_reg_433.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln14_fu_288_p2.read()))) {
        kc_0_reg_147 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln17_fu_318_p2.read(), ap_const_lv1_1))) {
        kr_0_reg_136 = kr_reg_415.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln11_fu_258_p2.read()))) {
        kr_0_reg_136 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln11_fu_258_p2.read(), ap_const_lv1_1))) {
        r_0_reg_112 = r_reg_384.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_0_reg_112 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln14_fu_288_p2.read()))) {
        add_ln19_1_reg_420 = add_ln19_1_fu_300_p2.read();
        shl_ln_reg_425 = shl_ln_fu_306_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c_reg_397 = c_fu_264_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        conv1_weight_load_reg_453 = conv1_weight_q0.read();
        input_load_reg_448 = input_r_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        kc_reg_433 = kc_fu_324_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        kr_reg_415 = kr_fu_294_p2.read();
        zext_ln14_reg_407 = zext_ln14_fu_284_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        mul_ln19_reg_376 = mul_ln19_fu_206_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln11_fu_258_p2.read()))) {
        output_addr_reg_402 =  (sc_lv<10>) (zext_ln19_1_fu_279_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_load_reg_463 = output_r_q0.read();
        tmp_reg_458 = grp_fu_162_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_reg_384 = r_fu_218_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_212_p2.read(), ap_const_lv1_0))) {
        sub_ln19_reg_389 = sub_ln19_fu_248_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        tmp_s_reg_468 = grp_fu_158_p2.read();
    }
}

void conv2_1::thread_add_ln19_1_fu_300_p2() {
    add_ln19_1_fu_300_p2 = (!zext_ln14_fu_284_p1.read().is_01() || !r_0_reg_112.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln14_fu_284_p1.read()) + sc_biguint<5>(r_0_reg_112.read()));
}

void conv2_1::thread_add_ln19_2_fu_330_p2() {
    add_ln19_2_fu_330_p2 = (!c_0_reg_124.read().is_01() || !zext_ln17_fu_314_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(c_0_reg_124.read()) + sc_biguint<5>(zext_ln17_fu_314_p1.read()));
}

void conv2_1::thread_add_ln19_3_fu_196_p2() {
    add_ln19_3_fu_196_p2 = (!sext_ln19_1_fu_188_p1.read().is_01() || !zext_ln19_5_fu_192_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(sext_ln19_1_fu_188_p1.read()) + sc_biguint<9>(zext_ln19_5_fu_192_p1.read()));
}

void conv2_1::thread_add_ln19_4_fu_352_p2() {
    add_ln19_4_fu_352_p2 = (!add_ln19_5_fu_347_p2.read().is_01() || !zext_ln14_reg_407.read().is_01())? sc_lv<5>(): (sc_biguint<5>(add_ln19_5_fu_347_p2.read()) + sc_biguint<5>(zext_ln14_reg_407.read()));
}

void conv2_1::thread_add_ln19_5_fu_347_p2() {
    add_ln19_5_fu_347_p2 = (!shl_ln_reg_425.read().is_01() || !zext_ln17_fu_314_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(shl_ln_reg_425.read()) + sc_biguint<5>(zext_ln17_fu_314_p1.read()));
}

void conv2_1::thread_add_ln19_6_fu_361_p2() {
    add_ln19_6_fu_361_p2 = (!zext_ln19_6_fu_357_p1.read().is_01() || !mul_ln19_reg_376.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln19_6_fu_357_p1.read()) + sc_biguint<12>(mul_ln19_reg_376.read()));
}

void conv2_1::thread_add_ln19_fu_270_p2() {
    add_ln19_fu_270_p2 = (!sub_ln19_reg_389.read().is_01() || !zext_ln11_fu_254_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(sub_ln19_reg_389.read()) + sc_biguint<11>(zext_ln11_fu_254_p1.read()));
}

void conv2_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv2_1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv2_1::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void conv2_1::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv2_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv2_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv2_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv2_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv2_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln8_fu_212_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_212_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2_1::thread_c_fu_264_p2() {
    c_fu_264_p2 = (!c_0_reg_124.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c_0_reg_124.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2_1::thread_conv1_weight_address0() {
    conv1_weight_address0 =  (sc_lv<11>) (sext_ln19_3_fu_366_p1.read());
}

void conv2_1::thread_conv1_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        conv1_weight_ce0 = ap_const_logic_1;
    } else {
        conv1_weight_ce0 = ap_const_logic_0;
    }
}

void conv2_1::thread_icmp_ln11_fu_258_p2() {
    icmp_ln11_fu_258_p2 = (!c_0_reg_124.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_124.read() == ap_const_lv5_1C);
}

void conv2_1::thread_icmp_ln14_fu_288_p2() {
    icmp_ln14_fu_288_p2 = (!kr_0_reg_136.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(kr_0_reg_136.read() == ap_const_lv3_5);
}

void conv2_1::thread_icmp_ln17_fu_318_p2() {
    icmp_ln17_fu_318_p2 = (!kc_0_reg_147.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(kc_0_reg_147.read() == ap_const_lv3_5);
}

void conv2_1::thread_icmp_ln8_fu_212_p2() {
    icmp_ln8_fu_212_p2 = (!r_0_reg_112.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_112.read() == ap_const_lv5_1C);
}

void conv2_1::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<12>) (tmp_19_fu_336_p5.read());
}

void conv2_1::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void conv2_1::thread_kc_fu_324_p2() {
    kc_fu_324_p2 = (!kc_0_reg_147.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(kc_0_reg_147.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2_1::thread_kr_fu_294_p2() {
    kr_fu_294_p2 = (!kr_0_reg_136.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(kr_0_reg_136.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2_1::thread_mul_ln19_fu_206_p0() {
    mul_ln19_fu_206_p0 = add_ln19_3_fu_196_p2.read();
}

void conv2_1::thread_mul_ln19_fu_206_p2() {
    mul_ln19_fu_206_p2 = (!mul_ln19_fu_206_p0.read().is_01() || !ap_const_lv12_19.is_01())? sc_lv<12>(): sc_bigint<9>(mul_ln19_fu_206_p0.read()) * sc_biguint<12>(ap_const_lv12_19);
}

void conv2_1::thread_output_r_address0() {
    output_r_address0 = output_addr_reg_402.read();
}

void conv2_1::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv2_1::thread_output_r_d0() {
    output_r_d0 = tmp_s_reg_468.read();
}

void conv2_1::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv2_1::thread_r_fu_218_p2() {
    r_fu_218_p2 = (!r_0_reg_112.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(r_0_reg_112.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2_1::thread_sext_ln19_1_fu_188_p1() {
    sext_ln19_1_fu_188_p1 = esl_sext<9,8>(sub_ln19_1_fu_182_p2.read());
}

void conv2_1::thread_sext_ln19_3_fu_366_p1() {
    sext_ln19_3_fu_366_p1 = esl_sext<64,12>(add_ln19_6_fu_361_p2.read());
}

void conv2_1::thread_sext_ln19_fu_275_p1() {
    sext_ln19_fu_275_p1 = esl_sext<32,11>(add_ln19_fu_270_p2.read());
}

void conv2_1::thread_shl_ln19_1_fu_224_p3() {
    shl_ln19_1_fu_224_p3 = esl_concat<5,5>(r_0_reg_112.read(), ap_const_lv5_0);
}

void conv2_1::thread_shl_ln19_2_fu_236_p3() {
    shl_ln19_2_fu_236_p3 = esl_concat<5,2>(r_0_reg_112.read(), ap_const_lv2_0);
}

void conv2_1::thread_shl_ln_fu_306_p3() {
    shl_ln_fu_306_p3 = esl_concat<3,2>(kr_0_reg_136.read(), ap_const_lv2_0);
}

void conv2_1::thread_sub_ln19_1_fu_182_p2() {
    sub_ln19_1_fu_182_p2 = (!zext_ln19_3_fu_178_p1.read().is_01() || !zext_ln19_fu_166_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln19_3_fu_178_p1.read()) - sc_biguint<8>(zext_ln19_fu_166_p1.read()));
}

void conv2_1::thread_sub_ln19_fu_248_p2() {
    sub_ln19_fu_248_p2 = (!zext_ln19_2_fu_232_p1.read().is_01() || !zext_ln19_4_fu_244_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln19_2_fu_232_p1.read()) - sc_biguint<11>(zext_ln19_4_fu_244_p1.read()));
}

void conv2_1::thread_tmp_18_fu_170_p3() {
    tmp_18_fu_170_p3 = esl_concat<5,2>(weight_offset.read(), ap_const_lv2_0);
}

void conv2_1::thread_tmp_19_fu_336_p5() {
    tmp_19_fu_336_p5 = esl_concat<59,5>(esl_concat<54,5>(esl_concat<52,2>(ap_const_lv52_0, input_offset.read()), add_ln19_1_reg_420.read()), add_ln19_2_fu_330_p2.read());
}

void conv2_1::thread_zext_ln11_fu_254_p1() {
    zext_ln11_fu_254_p1 = esl_zext<11,5>(c_0_reg_124.read());
}

void conv2_1::thread_zext_ln14_fu_284_p1() {
    zext_ln14_fu_284_p1 = esl_zext<5,3>(kr_0_reg_136.read());
}

void conv2_1::thread_zext_ln17_fu_314_p1() {
    zext_ln17_fu_314_p1 = esl_zext<5,3>(kc_0_reg_147.read());
}

void conv2_1::thread_zext_ln19_1_fu_279_p1() {
    zext_ln19_1_fu_279_p1 = esl_zext<64,32>(sext_ln19_fu_275_p1.read());
}

void conv2_1::thread_zext_ln19_2_fu_232_p1() {
    zext_ln19_2_fu_232_p1 = esl_zext<11,10>(shl_ln19_1_fu_224_p3.read());
}

void conv2_1::thread_zext_ln19_3_fu_178_p1() {
    zext_ln19_3_fu_178_p1 = esl_zext<8,7>(tmp_18_fu_170_p3.read());
}

void conv2_1::thread_zext_ln19_4_fu_244_p1() {
    zext_ln19_4_fu_244_p1 = esl_zext<11,7>(shl_ln19_2_fu_236_p3.read());
}

void conv2_1::thread_zext_ln19_5_fu_192_p1() {
    zext_ln19_5_fu_192_p1 = esl_zext<9,2>(input_offset.read());
}

void conv2_1::thread_zext_ln19_6_fu_357_p1() {
    zext_ln19_6_fu_357_p1 = esl_zext<12,5>(add_ln19_4_fu_352_p2.read());
}

void conv2_1::thread_zext_ln19_fu_166_p1() {
    zext_ln19_fu_166_p1 = esl_zext<8,5>(weight_offset.read());
}

void conv2_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_212_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln11_fu_258_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln14_fu_288_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln17_fu_318_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXX";
            break;
    }
}

}

