-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pool_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_offset : IN STD_LOGIC_VECTOR (4 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of pool_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv13_C4 : STD_LOGIC_VECTOR (12 downto 0) := "0000011000100";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv15_310 : STD_LOGIC_VECTOR (14 downto 0) := "000001100010000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal mul_ln30_fu_441_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln30_reg_447 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln30_1_fu_179_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln30_1_reg_453 : STD_LOGIC_VECTOR (12 downto 0);
    signal i_fu_191_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_461 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_ln30_fu_221_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln30_reg_466 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln28_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln30_4_fu_239_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln30_4_reg_471 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln30_1_fu_251_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln30_1_reg_476 : STD_LOGIC_VECTOR (8 downto 0);
    signal j_fu_267_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_484 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln29_fu_261_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_reg_494 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln33_fu_331_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln33_reg_504 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_fu_345_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_reg_512 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sub_ln33_fu_380_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln33_reg_517 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln31_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_fu_392_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal m_reg_525 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln32_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_load_1_reg_535 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal select_ln33_fu_434_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln33_reg_541 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal i_0_reg_98 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_0_reg_109 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_6_reg_121 : STD_LOGIC_VECTOR (15 downto 0);
    signal k_0_reg_131 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_8_reg_142 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal m_0_reg_154 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln30_1_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln30_3_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln33_1_fu_429_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln30_1_fu_179_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln30_1_fu_197_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln30_2_fu_209_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln30_fu_205_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln30_3_fu_217_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln30_3_fu_227_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln30_4_fu_235_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln30_5_fu_247_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln30_6_fu_273_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln30_1_fu_277_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_282_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln30_fu_290_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln30_2_fu_294_p2 : STD_LOGIC_VECTOR (14 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln30_2_fu_294_p2 : signal is "no";
    signal zext_ln29_fu_257_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln30_fu_304_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln30_2_fu_309_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln30_3_fu_313_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln_fu_323_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln31_fu_335_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln33_fu_351_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln33_1_fu_356_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln33_2_fu_368_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln33_1_fu_364_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln33_2_fu_376_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_fu_398_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_407_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln33_1_fu_415_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln33_fu_420_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln33_2_fu_424_p2 : STD_LOGIC_VECTOR (14 downto 0);
    attribute use_dsp48 of add_ln33_2_fu_424_p2 : signal is "no";
    signal grp_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln30_fu_441_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln30_fu_441_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln30_1_fu_179_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln30_fu_441_p00 : STD_LOGIC_VECTOR (14 downto 0);

    component my_net_hcmp_16ns_eOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component my_net_mul_mul_5nfYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;



begin
    my_net_hcmp_16ns_eOg_U10 : component my_net_hcmp_16ns_eOg
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_8_reg_142,
        din1 => input_r_q0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_4,
        dout => grp_fu_165_p2);

    my_net_mul_mul_5nfYi_U11 : component my_net_mul_mul_5nfYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 11,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln30_fu_441_p0,
        din1 => mul_ln30_fu_441_p1,
        dout => mul_ln30_fu_441_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    empty_6_reg_121_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln32_fu_386_p2 = ap_const_lv1_1))) then 
                empty_6_reg_121 <= empty_8_reg_142;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                empty_6_reg_121 <= input_r_q0;
            end if; 
        end if;
    end process;

    empty_8_reg_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_339_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                empty_8_reg_142 <= empty_6_reg_121;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                empty_8_reg_142 <= select_ln33_reg_541;
            end if; 
        end if;
    end process;

    i_0_reg_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln29_fu_261_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_98 <= i_reg_461;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_98 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    j_0_reg_109_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_339_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_0_reg_109 <= j_reg_484;
            elsif (((icmp_ln28_fu_185_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_109 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    k_0_reg_131_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln32_fu_386_p2 = ap_const_lv1_1))) then 
                k_0_reg_131 <= k_reg_512;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                k_0_reg_131 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    m_0_reg_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_339_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                m_0_reg_154 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                m_0_reg_154 <= m_reg_525;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_461 <= i_fu_191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                input_load_1_reg_535 <= input_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_reg_484 <= j_fu_267_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                k_reg_512 <= k_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                m_reg_525 <= m_fu_392_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    mul_ln30_1_reg_453(12 downto 2) <= mul_ln30_1_fu_179_p2(12 downto 2);
                mul_ln30_reg_447 <= mul_ln30_fu_441_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln29_fu_261_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                output_addr_reg_494 <= sext_ln30_3_fu_318_p1(12 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                select_ln33_reg_541 <= select_ln33_fu_434_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln28_fu_185_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    shl_ln30_4_reg_471(4 downto 1) <= shl_ln30_4_fu_239_p3(4 downto 1);
                    sub_ln30_1_reg_476(8 downto 1) <= sub_ln30_1_fu_251_p2(8 downto 1);
                    sub_ln30_reg_466(9 downto 2) <= sub_ln30_fu_221_p2(9 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_339_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    sub_ln33_reg_517(10 downto 2) <= sub_ln33_fu_380_p2(10 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    zext_ln33_reg_504(4 downto 1) <= zext_ln33_fu_331_p1(4 downto 1);
            end if;
        end if;
    end process;
    mul_ln30_1_reg_453(1 downto 0) <= "00";
    sub_ln30_reg_466(1 downto 0) <= "00";
    shl_ln30_4_reg_471(0) <= '0';
    sub_ln30_1_reg_476(0) <= '0';
    zext_ln33_reg_504(0) <= '0';
    zext_ln33_reg_504(10 downto 5) <= "000000";
    sub_ln33_reg_517(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln28_fu_185_p2, ap_CS_fsm_state3, icmp_ln29_fu_261_p2, ap_CS_fsm_state5, icmp_ln31_fu_339_p2, ap_CS_fsm_state6, icmp_ln32_fu_386_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln28_fu_185_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln29_fu_261_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln31_fu_339_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln32_fu_386_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln30_1_fu_277_p2 <= std_logic_vector(unsigned(sub_ln30_reg_466) + unsigned(zext_ln30_6_fu_273_p1));
    add_ln30_2_fu_294_p2 <= std_logic_vector(signed(sext_ln30_fu_290_p1) + signed(mul_ln30_reg_447));
    add_ln30_3_fu_313_p2 <= std_logic_vector(signed(sext_ln30_2_fu_309_p1) + signed(mul_ln30_1_reg_453));
    add_ln30_fu_304_p2 <= std_logic_vector(unsigned(zext_ln29_fu_257_p1) + unsigned(sub_ln30_1_reg_476));
    add_ln33_1_fu_415_p2 <= std_logic_vector(unsigned(zext_ln33_reg_504) + unsigned(tmp_fu_407_p3));
    add_ln33_2_fu_424_p2 <= std_logic_vector(signed(sext_ln33_fu_420_p1) + signed(mul_ln30_reg_447));
    add_ln33_fu_351_p2 <= std_logic_vector(unsigned(zext_ln31_fu_335_p1) + unsigned(shl_ln30_4_reg_471));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln28_fu_185_p2)
    begin
        if ((((icmp_ln28_fu_185_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln28_fu_185_p2)
    begin
        if (((icmp_ln28_fu_185_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_191_p2 <= std_logic_vector(unsigned(i_0_reg_98) + unsigned(ap_const_lv4_1));
    icmp_ln28_fu_185_p2 <= "1" when (i_0_reg_98 = ap_const_lv4_E) else "0";
    icmp_ln29_fu_261_p2 <= "1" when (j_0_reg_109 = ap_const_lv4_E) else "0";
    icmp_ln31_fu_339_p2 <= "1" when (k_0_reg_131 = ap_const_lv2_2) else "0";
    icmp_ln32_fu_386_p2 <= "1" when (m_0_reg_154 = ap_const_lv2_2) else "0";

    input_r_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state6, sext_ln30_1_fu_299_p1, sext_ln33_1_fu_429_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            input_r_address0 <= sext_ln33_1_fu_429_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_r_address0 <= sext_ln30_1_fu_299_p1(14 - 1 downto 0);
        else 
            input_r_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    input_r_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_fu_267_p2 <= std_logic_vector(unsigned(j_0_reg_109) + unsigned(ap_const_lv4_1));
    k_fu_345_p2 <= std_logic_vector(unsigned(k_0_reg_131) + unsigned(ap_const_lv2_1));
    m_fu_392_p2 <= std_logic_vector(unsigned(m_0_reg_154) + unsigned(ap_const_lv2_1));
    mul_ln30_1_fu_179_p0 <= mul_ln30_1_fu_179_p00(5 - 1 downto 0);
    mul_ln30_1_fu_179_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_offset),13));
    mul_ln30_1_fu_179_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln30_1_fu_179_p0) * unsigned(ap_const_lv13_C4), 13));
    mul_ln30_fu_441_p0 <= mul_ln30_fu_441_p00(5 - 1 downto 0);
    mul_ln30_fu_441_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_offset),15));
    mul_ln30_fu_441_p1 <= ap_const_lv15_310(11 - 1 downto 0);
    output_r_address0 <= output_addr_reg_494;

    output_r_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_d0_assign_proc : process(input_r_q0, ap_CS_fsm_state4, select_ln33_reg_541, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_r_d0 <= select_ln33_reg_541;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_d0 <= input_r_q0;
        else 
            output_r_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_we0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln33_fu_434_p3 <= 
        input_load_1_reg_535 when (grp_fu_165_p2(0) = '1') else 
        empty_8_reg_142;
        sext_ln30_1_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln30_2_fu_294_p2),64));

        sext_ln30_2_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln30_fu_304_p2),13));

        sext_ln30_3_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln30_3_fu_313_p2),64));

        sext_ln30_fu_290_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_282_p3),15));

        sext_ln33_1_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln33_2_fu_424_p2),64));

        sext_ln33_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln33_1_fu_415_p2),15));

    shl_ln30_1_fu_197_p3 <= (i_0_reg_98 & ap_const_lv5_0);
    shl_ln30_2_fu_209_p3 <= (i_0_reg_98 & ap_const_lv2_0);
    shl_ln30_3_fu_227_p3 <= (i_0_reg_98 & ap_const_lv4_0);
    shl_ln30_4_fu_239_p3 <= (i_0_reg_98 & ap_const_lv1_0);
    shl_ln33_1_fu_356_p3 <= (add_ln33_fu_351_p2 & ap_const_lv5_0);
    shl_ln33_2_fu_368_p3 <= (add_ln33_fu_351_p2 & ap_const_lv2_0);
    shl_ln_fu_323_p3 <= (j_0_reg_109 & ap_const_lv1_0);
    sub_ln30_1_fu_251_p2 <= std_logic_vector(unsigned(zext_ln30_4_fu_235_p1) - unsigned(zext_ln30_5_fu_247_p1));
    sub_ln30_fu_221_p2 <= std_logic_vector(unsigned(zext_ln30_fu_205_p1) - unsigned(zext_ln30_3_fu_217_p1));
    sub_ln33_fu_380_p2 <= std_logic_vector(unsigned(zext_ln33_1_fu_364_p1) - unsigned(zext_ln33_2_fu_376_p1));
    tmp_2_fu_398_p4 <= sub_ln33_reg_517(10 downto 2);
    tmp_3_fu_282_p3 <= (add_ln30_1_fu_277_p2 & ap_const_lv1_0);
    tmp_fu_407_p3 <= (tmp_2_fu_398_p4 & m_0_reg_154);
    zext_ln29_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_109),9));
    zext_ln30_3_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln30_2_fu_209_p3),10));
    zext_ln30_4_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln30_3_fu_227_p3),9));
    zext_ln30_5_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln30_4_fu_239_p3),9));
    zext_ln30_6_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_109),10));
    zext_ln30_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln30_1_fu_197_p3),10));
    zext_ln31_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_131),5));
    zext_ln33_1_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln33_1_fu_356_p3),11));
    zext_ln33_2_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln33_2_fu_368_p3),11));
    zext_ln33_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_323_p3),11));
end behav;
